### ISSUE TITLE
question

### ISSUE THREAD

**Issue by SANLANGWU** [SpaceNetLab/StarryNet#6]
when i run example.py,some problems happen:Traceback (most recent call last):
  File "./example.py", line 53, in <module>
    IP_list = sn.get_IP(node_index1)
  File "/Desktop/StarryNet/starrynet/sn_synchronizer.py", line 189, in get_IP
    ip_list.append(IP_info[i].split()[0])
IndexError: list index out of range
I don't know if it's my container or the code

**Comment by yangtaodeng** [comment]
> when i run example.py,some problems happen:Traceback (most recent call last): File "./example.py", line 53, in IP_list = sn.get_IP(node_index1) File "/Desktop/StarryNet/starrynet/sn_synchronizer.py", line 189, in get_IP ip_list.append(IP_info[i].split()[0]) IndexError: list index out of range I don't know if it's my container or the code

Hi, it seems the node_index1 is wrong or out of range. Please check it with the satellite number and ground station number. By the way, we recommend you run it on a high-performance server with multiple CPUs.
